# GENERATED by api/tools/v3_approval_conformance.py from api/tests/fixtures/v3_approval/cases.json; do not edit.
# Every case must give exactly the codes the Python validator and the staging build give for it.

run "approved" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approved.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/approved.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == []
    error_message = "approved: got ${jsonencode(output.codes)}"
  }
}

run "approved_non_expiring" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approved-non-expiring.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/approved-non-expiring.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == []
    error_message = "approved_non_expiring: got ${jsonencode(output.codes)}"
  }
}

run "future_review" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/future-review.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/future-review.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == []
    error_message = "future_review: got ${jsonencode(output.codes)}"
  }
}

run "review_on_the_90th_day_is_accepted" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approved.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/approved.json"), null)
    today        = "2026-12-29"
  }
  assert {
    condition     = output.codes == []
    error_message = "review_on_the_90th_day_is_accepted: got ${jsonencode(output.codes)}"
  }
}

run "review_reached" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approved.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/approved.json"), null)
    today        = "2026-12-30"
  }
  assert {
    condition     = output.codes == ["REVIEW_REACHED"]
    error_message = "review_reached: got ${jsonencode(output.codes)}"
  }
}

run "review_window_exceeded" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/review-window-exceeded.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/review-window-exceeded.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["REVIEW_WINDOW"]
    error_message = "review_window_exceeded: got ${jsonencode(output.codes)}"
  }
}

run "review_not_after_approval" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/review-not-after-approval.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/review-not-after-approval.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["REVIEW_WINDOW", "REVIEW_REACHED"]
    error_message = "review_not_after_approval: got ${jsonencode(output.codes)}"
  }
}

run "review_missing" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/review-missing.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/review-missing.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["REVIEW_WINDOW"]
    error_message = "review_missing: got ${jsonencode(output.codes)}"
  }
}

run "review_date_as_number" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/review-date-as-number.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/review-date-as-number.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["REVIEW_WINDOW"]
    error_message = "review_date_as_number: got ${jsonencode(output.codes)}"
  }
}

run "expired" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/expired.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/expired.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["EXPIRED"]
    error_message = "expired: got ${jsonencode(output.codes)}"
  }
}

run "expired_on_its_expiry_day" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approved.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/approved.json"), null)
    today        = "2027-03-31"
  }
  assert {
    condition     = output.codes == ["REVIEW_REACHED", "EXPIRED"]
    error_message = "expired_on_its_expiry_day: got ${jsonencode(output.codes)}"
  }
}

run "expiry_before_approval" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/expiry-before-approval.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/expiry-before-approval.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["EXPIRY_POLICY", "EXPIRED"]
    error_message = "expiry_before_approval: got ${jsonencode(output.codes)}"
  }
}

run "no_expiry_policy" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/no-expiry-policy.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/no-expiry-policy.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["EXPIRY_POLICY"]
    error_message = "no_expiry_policy: got ${jsonencode(output.codes)}"
  }
}

run "expiry_and_non_expiring" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/expiry-and-non-expiring.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/expiry-and-non-expiring.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["EXPIRY_POLICY"]
    error_message = "expiry_and_non_expiring: got ${jsonencode(output.codes)}"
  }
}

run "non_expiring_too_short" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/non-expiring-too-short.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/non-expiring-too-short.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["EXPIRY_POLICY"]
    error_message = "non_expiring_too_short: got ${jsonencode(output.codes)}"
  }
}

run "approval_in_future" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approval-in-future.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/approval-in-future.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["APPROVAL_IN_FUTURE"]
    error_message = "approval_in_future: got ${jsonencode(output.codes)}"
  }
}

run "approval_date_not_a_day" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approval-date-not-a-day.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/approval-date-not-a-day.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["APPROVAL_DATE"]
    error_message = "approval_date_not_a_day: got ${jsonencode(output.codes)}"
  }
}

run "revoked" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/revoked.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/revoked.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["STATUS", "REVOKED"]
    error_message = "revoked: got ${jsonencode(output.codes)}"
  }
}

run "revocation_on_approved" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/revocation-on-approved.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/revocation-on-approved.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["REVOKED"]
    error_message = "revocation_on_approved: got ${jsonencode(output.codes)}"
  }
}

run "draft" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/draft.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/draft.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["STATUS"]
    error_message = "draft: got ${jsonencode(output.codes)}"
  }
}

run "in_review" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/in-review.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/in-review.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["STATUS"]
    error_message = "in_review: got ${jsonencode(output.codes)}"
  }
}

run "wrong_environment" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/wrong-environment.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/wrong-environment.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["ENVIRONMENT"]
    error_message = "wrong_environment: got ${jsonencode(output.codes)}"
  }
}

run "schema_1" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/schema-1.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/schema-1.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["SCHEMA"]
    error_message = "schema_1: got ${jsonencode(output.codes)}"
  }
}

run "digest_mismatch" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approved.json"
    bound_sha256 = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["DIGEST_MISMATCH"]
    error_message = "digest_mismatch: got ${jsonencode(output.codes)}"
  }
}

run "digest_unbound" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/approved.json"
    bound_sha256 = null
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["DIGEST_MISMATCH"]
    error_message = "digest_unbound: got ${jsonencode(output.codes)}"
  }
}

run "self_approved" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/self-approved.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/self-approved.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["APPROVER"]
    error_message = "self_approved: got ${jsonencode(output.codes)}"
  }
}

run "placeholder_approver" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/placeholder-approver.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/placeholder-approver.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["APPROVER"]
    error_message = "placeholder_approver: got ${jsonencode(output.codes)}"
  }
}

run "missing_evidence" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/missing-evidence.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/missing-evidence.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["EVIDENCE"]
    error_message = "missing_evidence: got ${jsonencode(output.codes)}"
  }
}

run "unknown_evidence" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/unknown-evidence.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/unknown-evidence.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["EVIDENCE"]
    error_message = "unknown_evidence: got ${jsonencode(output.codes)}"
  }
}

run "evidence_sha_not_lowercase_hex" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/evidence-sha-not-lowercase-hex.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/evidence-sha-not-lowercase-hex.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["EVIDENCE"]
    error_message = "evidence_sha_not_lowercase_hex: got ${jsonencode(output.codes)}"
  }
}

run "wrong_scope_public_intake" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/wrong-scope-public-intake.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/wrong-scope-public-intake.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["SCOPE"]
    error_message = "wrong_scope_public_intake: got ${jsonencode(output.codes)}"
  }
}

run "wrong_scope_unprotected" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/wrong-scope-unprotected.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/wrong-scope-unprotected.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["SCOPE"]
    error_message = "wrong_scope_unprotected: got ${jsonencode(output.codes)}"
  }
}

run "wrong_scope_3d" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/wrong-scope-3d.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/wrong-scope-3d.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["SCOPE"]
    error_message = "wrong_scope_3d: got ${jsonencode(output.codes)}"
  }
}

run "wrong_scope_boolean_as_string" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/wrong-scope-boolean-as-string.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/wrong-scope-boolean-as-string.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["SCOPE"]
    error_message = "wrong_scope_boolean_as_string: got ${jsonencode(output.codes)}"
  }
}

run "bad_release" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/bad-release.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/bad-release.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["RELEASE"]
    error_message = "bad_release: got ${jsonencode(output.codes)}"
  }
}

run "malformed_array" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/malformed-array.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/malformed-array.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["MALFORMED"]
    error_message = "malformed_array: got ${jsonencode(output.codes)}"
  }
}

run "malformed_text" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/malformed-text.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/malformed-text.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["MALFORMED"]
    error_message = "malformed_text: got ${jsonencode(output.codes)}"
  }
}

run "no_record" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/no-such-record.json"
    bound_sha256 = try(filesha256("../../../../api/tests/fixtures/v3_approval/no-such-record.json"), null)
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["NO_RECORD"]
    error_message = "no_record: got ${jsonencode(output.codes)}"
  }
}

run "committed_draft_template" {
  command = plan
  variables {
    record_path  = "../../../../api/tests/fixtures/v3_approval/../../../../docs/implementation/catalog/v3-staging-approval.template.json"
    bound_sha256 = null
    today        = "2026-10-11"
  }
  assert {
    condition     = output.codes == ["STATUS", "APPROVER", "APPROVAL_DATE", "REVIEW_WINDOW", "EXPIRY_POLICY", "EVIDENCE", "DIGEST_MISMATCH"]
    error_message = "committed_draft_template: got ${jsonencode(output.codes)}"
  }
}
