"""ADR-002 identifiers, PLAT-007 time handling, RFC 8785 canonicalization."""

from datetime import UTC, date, datetime

import pytest

from veda.kernel import clock
from veda.kernel.ids import ANONYMOUS_USER_ID, SYSTEM_USER_ID, WEB_INTAKE_USER_ID, is_valid_id, new_id
from veda.kernel.jcs import canonicalize


def test_DATA_002_uuidv7_canonical_form():
    ids = [new_id() for _ in range(2000)]
    assert all(is_valid_id(i) for i in ids)
    assert all(len(i) == 32 and i == i.lower() and "-" not in i for i in ids)
    assert ids == sorted(ids), "ids generated by one process are monotonic"
    assert len(set(ids)) == len(ids)


@pytest.mark.parametrize("value", [
    "0192A4F1C3B27E8D9F10A2B3C4D5E6F7",          # uppercase
    "0192a4f1-c3b2-7e8d-9f10-a2b3c4d5e6f7",      # hyphenated
    "0192a4f1c3b24e8d9f10a2b3c4d5e6f7",          # version 4
    "0192a4f1c3b27e8d7f10a2b3c4d5e6f7",          # bad variant
    "123", "", None, 42,
])
def test_DATA_013_non_canonical_ids_rejected(value):
    assert not is_valid_id(value)


def test_seeded_system_actor_ids_are_valid():
    assert all(is_valid_id(i) for i in (SYSTEM_USER_ID, WEB_INTAKE_USER_ID, ANONYMOUS_USER_ID))


def test_PLAT_007_offsetless_datetimes_rejected():
    with pytest.raises(ValueError):
        clock.parse_rfc3339("2026-09-30T11:00:00")
    assert clock.parse_rfc3339("2026-09-30T11:00:00+05:30") == datetime(2026, 9, 30, 5, 30, tzinfo=UTC)
    assert clock.parse_rfc3339("2026-09-30T05:30:00Z") == datetime(2026, 9, 30, 5, 30, tzinfo=UTC)


def test_PLAT_007_local_day_ranges_are_half_open_utc():
    start, end = clock.local_day_range_utc(date(2026, 9, 1), date(2026, 9, 30), "Asia/Kolkata")
    assert start == datetime(2026, 8, 31, 18, 30, tzinfo=UTC)
    assert end == datetime(2026, 9, 30, 18, 30, tzinfo=UTC)


def test_rfc3339_rendering():
    t = datetime(2026, 9, 29, 10, 2, 11, 4211, tzinfo=UTC)
    assert clock.to_rfc3339(t) == "2026-09-29T10:02:11.004Z"
    assert clock.to_rfc3339(t, micros=True) == "2026-09-29T10:02:11.004211Z"


def test_jcs_rfc8785_vectors():
    assert canonicalize({"b": 2, "a": [1, True, None, "x"]}) == '{"a":[1,true,null,"x"],"b":2}'
    # Keys sort by UTF-16 code units, not code points (RFC 8785 §3.2.3).
    assert canonicalize({"\U0001F600": 1, "ﬁ": 2}) == '{"\U0001F600":1,"ﬁ":2}'
    assert canonicalize("line\nbreak\u0001") == '"line\\nbreak\\u0001"'
    with pytest.raises(TypeError):
        canonicalize(1.5)
