#!/usr/bin/env bash
# One-time bootstrap of the dedicated Veda staging AWS account (plan §8, AUT-003).
#
#   infra/scripts/bootstrap.sh --expected-account-id 123456789012                # plan only (default)
#   infra/scripts/bootstrap.sh --expected-account-id 123456789012 --mode apply   # asks to type the account ID
#   ... --mode apply --yes                                                        # non-interactive (00-bootstrap)
#
# Options: --repo owner/repo (default: discovered) · --skip-guardrails (account already manages them)
#
# Credentials: a temporary owner session in the Veda account (AWS_ACCESS_KEY_ID/SECRET/SESSION_TOKEN or a
# profile). The session must be for --expected-account-id; the Terraform provider refuses any other account too.
#
# plan  : discovery + terraform plan. Read-only; nothing is created.
# apply : applies that plan, then moves the state into the bucket it created (first run) and writes
#         infra/generated/bootstrap-outputs.json for github-setup.sh.
set -euo pipefail
# shellcheck source=lib.sh
source "$(dirname "$0")/lib.sh"

MODE="plan"
EXPECTED=""
REPO_ARG=""
YES=0
SKIP_GUARDRAILS=0
while (($#)); do
  case "$1" in
    --mode) MODE="${2:-}"; shift 2 ;;
    --expected-account-id) EXPECTED="${2:-}"; shift 2 ;;
    --repo) REPO_ARG="${2:-}"; shift 2 ;;
    --yes) YES=1; shift ;;
    --skip-guardrails) SKIP_GUARDRAILS=1; shift ;;
    -h | --help) sed -n '2,17p' "$0"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ "$MODE" == "plan" || "$MODE" == "apply" ]] || die "--mode must be plan or apply"
require_tools aws jq terraform curl git
require_account_id "$EXPECTED"
require_region
require_expected_account "$EXPECTED"
export TF_IN_AUTOMATION=1 TF_INPUT=0

discover_args=(--expected-account-id "$EXPECTED")
[[ -n "$REPO_ARG" ]] && discover_args+=(--repo "$REPO_ARG")
"$INFRA_DIR/scripts/discover.sh" "${discover_args[@]}"
DISCOVERED="$GENERATED_DIR/discovered.json"

if ((SKIP_GUARDRAILS)); then
  jq '. + {enable_account_guardrails: false}' "$BOOTSTRAP_DIR/generated.auto.tfvars.json" >"$BOOTSTRAP_DIR/tmp.json"
  mv "$BOOTSTRAP_DIR/tmp.json" "$BOOTSTRAP_DIR/generated.auto.tfvars.json"
fi

BUCKET="$(jq -r .aws.state_bucket "$DISCOVERED")"
STATE_EXISTS="$(jq -r .aws.state_bucket_exists "$DISCOVERED")"
STATE_KEY="bootstrap/terraform.tfstate"
BACKEND_FILE="$BOOTSTRAP_DIR/backend_s3.tf"
PLAN_FILE="$GENERATED_DIR/bootstrap.tfplan"

write_backend() {
  cat >"$BACKEND_FILE" <<'EOF'
# Generated by infra/scripts/bootstrap.sh once the state bucket exists. Do not commit (gitignored).
terraform {
  backend "s3" {}
}
EOF
}

# Sets BARGS (bash 3.2 compatible: macOS operators run this with the system bash).
backend_args() {
  BARGS=("-backend-config=bucket=$BUCKET" "-backend-config=key=$STATE_KEY"
    "-backend-config=region=$VEDA_REGION" "-backend-config=encrypt=true"
    "-backend-config=kms_key_id=$1" "-backend-config=use_lockfile=true")
}

cd "$BOOTSTRAP_DIR"
if [[ "$STATE_EXISTS" == "true" ]]; then
  KEY_ARN="$(jq -r .aws.state_kms_key_arn "$DISCOVERED")"
  [[ -n "$KEY_ARN" ]] || die "state bucket $BUCKET exists but alias/${VEDA_PREFIX}-tfstate does not"
  [[ -f terraform.tfstate ]] && die "local terraform.tfstate present while $BUCKET exists: resolve manually (docs/operations/staging-bootstrap.md §6)"
  log "remote state: s3://$BUCKET/$STATE_KEY"
  write_backend
  backend_args "$KEY_ARN"
  terraform init -reconfigure -input=false "${BARGS[@]}" >/dev/null
else
  log "first run: local state, migrated to s3://$BUCKET after apply"
  rm -f "$BACKEND_FILE"
  terraform init -reconfigure -input=false >/dev/null
fi

terraform plan -input=false -lock-timeout=5m -out="$PLAN_FILE"
terraform show -no-color "$PLAN_FILE" >"$GENERATED_DIR/bootstrap-plan.txt"
log "plan written to $GENERATED_DIR/bootstrap-plan.txt"

if [[ "$MODE" == "plan" ]]; then
  log "plan mode: nothing was created"
  exit 0
fi

if ((!YES)); then
  read -r -p "Apply the bootstrap plan to AWS account $EXPECTED? Type the account ID to confirm: " answer
  [[ "$answer" == "$EXPECTED" ]] || die "not confirmed"
fi

terraform apply -input=false -lock-timeout=5m "$PLAN_FILE"
rm -f "$PLAN_FILE"

if [[ "$STATE_EXISTS" != "true" ]]; then
  KEY_ARN="$(terraform output -raw state_kms_key_arn)"
  log "migrating state into s3://$BUCKET/$STATE_KEY"
  write_backend
  backend_args "$KEY_ARN"
  terraform init -migrate-state -force-copy -input=false "${BARGS[@]}" >/dev/null
  aws s3api head-object --bucket "$BUCKET" --key "$STATE_KEY" >/dev/null ||
    die "state migration could not be verified; keep terraform.tfstate and see the runbook §6"
  rm -f terraform.tfstate terraform.tfstate.backup
  log "state migrated and verified; local copy removed"
fi

terraform output -json | jq '{
  account_id: .account_id.value, region: .region.value,
  state_bucket: .state_bucket.value, state_kms_key_arn: .state_kms_key_arn.value,
  github_oidc_provider_arn: .github_oidc_provider_arn.value,
  permissions_boundary_arn: .permissions_boundary_arn.value,
  github_role_arns: .github_role_arns.value, github_environments: .github_environments.value,
  backend_config: .backend_config.value
}' >"$GENERATED_DIR/bootstrap-outputs.json"
log "wrote $GENERATED_DIR/bootstrap-outputs.json"
log "next: infra/scripts/github-setup.sh --outputs $GENERATED_DIR/bootstrap-outputs.json --variables-only --apply"
