"""UUIDv7 identifiers in canonical 32-hex form (ADR-002, 03 §2.2).

Ids are generated by the service layer before insert, never by the database.
The canonical external form is exactly 32 lowercase hex characters with the
version nibble ``7`` and an RFC 9562 variant nibble (``8``..``b``).
"""

from __future__ import annotations

import re
import secrets
import threading
import time

UUID7_PATTERN = r"^[0-9a-f]{12}7[0-9a-f]{3}[89ab][0-9a-f]{15}$"
_UUID7_RE = re.compile(UUID7_PATTERN)

# Seeded system actors (03 §2.3). Valid UUIDv7 form with timestamp 0.
SYSTEM_USER_ID = "00000000000070008000000000000001"
WEB_INTAKE_USER_ID = "00000000000070008000000000000002"
ANONYMOUS_USER_ID = "00000000000070008000000000000003"
SYSTEM_ACTOR_IDS = frozenset({SYSTEM_USER_ID, WEB_INTAKE_USER_ID, ANONYMOUS_USER_ID})

_lock = threading.Lock()
_last_ms = 0
_last_rand_a = 0


def new_id() -> str:
    """Return a new UUIDv7 as 32 lowercase hex characters.

    Within one millisecond the 12-bit ``rand_a`` field is used as a counter so
    ids generated by this process are strictly increasing (RFC 9562 method 1).
    """
    global _last_ms, _last_rand_a
    with _lock:
        ms = time.time_ns() // 1_000_000
        if ms <= _last_ms:
            ms = _last_ms
            _last_rand_a += 1
            if _last_rand_a > 0xFFF:
                ms += 1
                _last_rand_a = secrets.randbits(11)
        else:
            _last_rand_a = secrets.randbits(11)
        _last_ms = ms
        rand_a = _last_rand_a
    rand_b = secrets.randbits(62)
    value = (ms & 0xFFFFFFFFFFFF) << 80
    value |= 0x7 << 76
    value |= rand_a << 64
    value |= 0b10 << 62
    value |= rand_b
    return f"{value:032x}"


def is_valid_id(value: object) -> bool:
    return isinstance(value, str) and _UUID7_RE.match(value) is not None


def id_timestamp_ms(value: str) -> int:
    return int(value[:12], 16)
