"""Generate the customer-text inventory of the catalog (V3 customer-safety closure) from the field registry.

    python tools/catalog_text_inventory.py            # print
    python tools/catalog_text_inventory.py --write    # write docs/implementation/catalog/CATALOG-V3-customer-text-inventory.md

`tests/unit/test_catalog_text_inventory.py` fails when a text field is unclassified or this document is out of date.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from veda.modules.catalog import kinds, public, text  # noqa: E402

DOC = Path(__file__).resolve().parents[2] / "docs/implementation/catalog/CATALOG-V3-customer-text-inventory.md"

ROWS = {
    text.FACTUAL: ("factual (no promise, no claim)", "no: promise and claim wording refused", "no (refused)",
                   "yes", "text gate refuses promise, claim or forbidden wording"),
    text.STATEMENT: ("statement: factual, promise or claim", "yes: it is a copy record", "yes, when a promise",
                     "yes", "text gate; a promise needs its confirmed matrix row; a claim needs approved claim governance"),
    text.STAFF: ("staff only", "n/a", "n/a", "no (stripped from the customer view)", "n/a"),
    text.IDENTIFIER: ("identifier (key, code, choice, hash, URL, date)", "n/a", "n/a", "as an identifier, not prose",
                      "schema and reference checks"),
}  # fmt: skip


PUBLIC_CHECKS = {
    public.FACTUAL_CUSTOMER_COPY: "canonical form: no invisible character, rate, amount, contact, duration, promise or claim",
    public.CONTROLLED_CUSTOMER_COPY: "must equal its release copy record (canonical form); a claim needs governance; a promise needs its matrix row",
    public.PROMISE_GOVERNED_COPY: "promise-matrix scope (V2 matrix rows); canonical form: no rate, amount, contact or marketing claim",
    public.MARKETING_CLAIM_COPY: "only through a governed claim copy record",
    public.PRICE_OR_RATE_COPY: "an engine total or range (integer); never text",
    public.STAFF_ONLY: "never in a public payload",
    public.IDENTIFIER: "schema, pattern and reference checks; not prose",
    public.NOT_CUSTOMER_VISIBLE: "ordering or flags; not rendered as text",
}  # fmt: skip


def entities() -> dict[str, list[str]]:
    """Which record kinds reach each declaring model."""
    out: dict[str, set[str]] = {}
    for kind, cls in kinds.SCHEMAS.items():
        for decl, _field in text.string_fields([cls]):
            out.setdefault(decl, set()).add(kind)
    return {k: sorted(v) for k, v in out.items()}


def render() -> str:
    reach = entities()
    lines = [
        "# Catalog V3 customer-text inventory (generated)",
        "",
        "Generated by `api/tools/catalog_text_inventory.py` from `veda.modules.catalog.public.PUBLIC_FIELD_CLASSES` and",
        "`veda.modules.catalog.text.FIELD_CLASSES`. Do not edit by hand: `tests/unit/test_catalog_text_inventory.py` fails",
        "when this file is stale.",
        "",
        "Two inventories, both machine-checked:",
        "",
        "1. **Public payloads** (what a customer receives): every field of the strict public DTOs that the catalog and",
        "   estimate serialisers build (`veda.modules.catalog.public`), in eight classes. CI fails on an unclassified field",
        "   or a weak type (`test_catalog_canonical_copy.py`). Release validation and both serialisers run the same",
        "   canonical checks over these payloads (`test_catalog_public_payload.py`).",
        "2. **Catalog records** (what staff author): every string-bearing field of the catalog models, in four authoring",
        "   classes (`test_catalog_text_inventory.py`, `test_catalog_claims.py`).",
        "",
        "## 1. Public payloads (catalog, estimate) and card customer text",
        "",
        "| Payload DTO | Field | Class | Checks |",
        "|---|---|---|---|",
    ]
    for (dto, field), cls in sorted(public.PUBLIC_FIELD_CLASSES.items()):
        lines.append(f"| {dto} | `{field}` | {cls} | {PUBLIC_CHECKS[cls]} |")
    lines += [
        "",
        "Customer-visible text kept in the staff-only pricing card (governed although the card is private): exclusions,",
        "client scope, timeline labels, site-package component labels and inclusions, product labels and input labels",
        "(`public.card_texts`). Each is checked as PROMISE_GOVERNED_COPY at release validation.",
        "",
        "Public totals, ranges and rounded room subtotals are PRICE_OR_RATE_COPY: integers computed by the engine, never",
        "text. Internal unit rates, line amounts, margins, procurement or supplier prices are in no public DTO and are",
        "refused in every customer string.",
        "",
        "## 2. Catalog records (authoring)",
        "",
        "| Entity (record kinds) | Field | Class | Governed copy | Promise matrix | Public | Release gate |",
        "|---|---|---|---|---|---|---|",
    ]
    for decl, field in sorted(text.string_fields(kinds.SCHEMAS.values())):
        cls = text.FIELD_CLASSES[(decl, field)]
        label, governed, matrix, shown, gate = ROWS[cls]
        lines.append(
            f"| {decl} ({', '.join(reach.get(decl, []))}) | `{field}` | {label} | {governed} | {matrix} | {shown} | {gate} |"
        )
    lines += ["", "Fields named by the instruction that the catalog does not have (so they carry no text):", ""]
    lines += [f"- {name}" for name in text.NOT_IN_SCHEMA]
    lines += ["", "`Package.recommended` is a boolean; the page does not render it as text. Rendering a recommendation",
              "label would need an approved claim copy record.", ""]  # fmt: skip
    return "\n".join(lines)


if __name__ == "__main__":
    out = render()
    if "--write" in sys.argv:
        DOC.write_text(out)
        print(f"wrote {DOC}")
    else:
        print(out)
