"""Generate the customer-text inventory of the catalog (V3 customer-safety closure) from the field registry.

    python tools/catalog_text_inventory.py            # print
    python tools/catalog_text_inventory.py --write    # write docs/implementation/catalog/CATALOG-V3-customer-text-inventory.md

`tests/unit/test_catalog_text_inventory.py` fails when a text field is unclassified or this document is out of date.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from veda.modules.catalog import kinds, public, text  # noqa: E402

DOC = Path(__file__).resolve().parents[2] / "docs/implementation/catalog/CATALOG-V3-customer-text-inventory.md"

ROWS = {
    text.FACTUAL: ("factual (no promise, no claim)", "no: promise and claim wording refused", "no (refused)",
                   "yes", "text gate refuses promise, claim or forbidden wording"),
    text.STATEMENT: ("statement: factual, promise or claim", "yes: it is a copy record", "yes, when a promise",
                     "yes", "text gate; a promise needs its confirmed matrix row; a claim needs approved claim governance"),
    text.STAFF: ("staff only", "n/a", "n/a", "no (stripped from the customer view)", "n/a"),
    text.IDENTIFIER: ("identifier (key, code, choice, hash, URL, date)", "n/a", "n/a", "as an identifier, not prose",
                      "schema and reference checks"),
}  # fmt: skip


PUBLIC_CHECKS = {
    public.FACTUAL_TEXT: "no claim of any category, promise wording, money, rate, pricing wording, duration or contact detail",
    public.GOVERNED_CLAIM_REFERENCE: "the approved text of a claim or promise record of the release, valid at serve time (approved, owned, in effect, before review date, not withdrawn, permitted environment, applicable)",
    public.ENGINE_GENERATED_AMOUNT: "an integer computed by the engine from the approved card named by pricing_card_version; never text",
    public.STRUCTURED_MEASUREMENT: "a number, a unit enum or a measurement type (never a rate or total amount)",
    public.STRUCTURED_TIMELINE: "day ranges and the card's versioned timeline wording: durations allowed; no money or claim (no delivery commitment)",
    public.STRUCTURED_ASSUMPTION: "parts of a typical-size assumption (labels from the versioned card): no money or claim",
    public.STRUCTURED_EXCLUSION: "the card's versioned exclusion items: no money or claim",
    public.STRUCTURED_CLIENT_SCOPE: "the card's versioned client-scope items: no money or claim",
    public.CONTROLLED_LEGAL_COPY: "allowlisted estimator wording, or the approved text of a non-claim copy record: no money or claim",
    public.STAFF_ONLY: "never in a public payload",
    public.IDENTIFIER: "keys, codes, enums, flags, ordering, hashes, dates: schema and pattern checks; not prose",
}  # fmt: skip


def entities() -> dict[str, list[str]]:
    """Which record kinds reach each declaring model."""
    out: dict[str, set[str]] = {}
    for kind, cls in kinds.SCHEMAS.items():
        for decl, _field in text.string_fields([cls]):
            out.setdefault(decl, set()).add(kind)
    return {k: sorted(v) for k, v in out.items()}


def render() -> str:
    reach = entities()
    lines = [
        "# Catalog V3 customer-text inventory (generated)",
        "",
        "Generated by `api/tools/catalog_text_inventory.py` from `veda.modules.catalog.public.PUBLIC_FIELD_POLICIES` and",
        "`veda.modules.catalog.text.FIELD_CLASSES`. Do not edit by hand: `tests/unit/test_catalog_text_inventory.py` fails",
        "when this file is stale.",
        "",
        "Two inventories, both machine-checked:",
        "",
        "1. **Public payloads** (what a customer receives): every field of the strict public DTOs that the catalog and",
        "   estimate serialisers build (`veda.modules.catalog.public`), each with exactly one of eleven content policies. CI fails on an unclassified field",
        "   or a weak type (`test_catalog_canonical_copy.py`). Release validation and both serialisers run the same",
        "   canonical checks over these payloads (`test_catalog_public_payload.py`).",
        "2. **Catalog records** (what staff author): every string-bearing field of the catalog models, in four authoring",
        "   classes (`test_catalog_text_inventory.py`, `test_catalog_claims.py`).",
        "",
        "## 1. Public payloads (catalog, estimate) and card customer text",
        "",
        "| Payload DTO | Field | Content policy | Checks |",
        "|---|---|---|---|",
    ]
    for (dto, field), cls in sorted(public.PUBLIC_FIELD_POLICIES.items()):
        lines.append(f"| {dto} | `{field}` | {cls} | {PUBLIC_CHECKS[cls]} |")
    lines += [
        "",
        "Customer-visible text kept in the staff-only pricing card (governed although the card is private): exclusions,",
        "client scope, timeline labels, site-package component labels and inclusions, product labels and input labels",
        "(`public.card_texts`). Each is checked at release validation under its policy: STRUCTURED_EXCLUSION,",
        "STRUCTURED_CLIENT_SCOPE, STRUCTURED_TIMELINE, STRUCTURED_ASSUMPTION or FACTUAL_TEXT. None may carry money or",
        "a claim.",
        "",
        "Public money is only ENGINE_GENERATED_AMOUNT: the range, GST, rounded room subtotals, the site-package amount",
        "and the allowance band, as integers computed by the engine from the card the estimate names",
        "(`pricing_card_version`). Internal unit rates, line amounts, margins, procurement or supplier prices are in no",
        "public DTO. No customer prose may carry money; detection in prose is defence in depth.",
        "",
        "Typical-size assumptions are structured (`PublicAssumption`: a value, a unit enum FT, SQ_FT or NOS, and a type",
        "LENGTH, AREA, QUANTITY or DIMENSION). RATE and TOTAL_AMOUNT are never public measurement types.",
        "",
        "## 2. Catalog records (authoring)",
        "",
        "| Entity (record kinds) | Field | Class | Governed copy | Promise matrix | Public | Release gate |",
        "|---|---|---|---|---|---|---|",
    ]
    for decl, field in sorted(text.string_fields(kinds.SCHEMAS.values())):
        cls = text.FIELD_CLASSES[(decl, field)]
        label, governed, matrix, shown, gate = ROWS[cls]
        lines.append(
            f"| {decl} ({', '.join(reach.get(decl, []))}) | `{field}` | {label} | {governed} | {matrix} | {shown} | {gate} |"
        )
    lines += ["", "Fields named by the instruction that the catalog does not have (so they carry no text):", ""]
    lines += [f"- {name}" for name in text.NOT_IN_SCHEMA]
    lines += ["", "`Package.recommended` is a boolean; the page does not render it as text. Rendering a recommendation",
              "label would need an approved claim copy record.", ""]  # fmt: skip
    return "\n".join(lines)


if __name__ == "__main__":
    out = render()
    if "--write" in sys.argv:
        DOC.write_text(out)
        print(f"wrote {DOC}")
    else:
        print(out)
