"""Generate the customer-text inventory of the catalog (V3 customer-safety closure) from the field registry.

    python tools/catalog_text_inventory.py            # print
    python tools/catalog_text_inventory.py --write    # write docs/implementation/catalog/CATALOG-V3-customer-text-inventory.md

`tests/unit/test_catalog_text_inventory.py` fails when a text field is unclassified or this document is out of date.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from veda.modules.catalog import kinds, text  # noqa: E402

DOC = Path(__file__).resolve().parents[2] / "docs/implementation/catalog/CATALOG-V3-customer-text-inventory.md"

ROWS = {
    text.FACTUAL: ("factual (no promise, no claim)", "no: promise and claim wording refused", "no (refused)",
                   "yes", "text gate refuses promise, claim or forbidden wording"),
    text.STATEMENT: ("statement: factual, promise or claim", "yes: it is a copy record", "yes, when a promise",
                     "yes", "text gate; a promise needs its confirmed matrix row; a claim needs approved claim governance"),
    text.STAFF: ("staff only", "n/a", "n/a", "no (stripped from the customer view)", "n/a"),
    text.IDENTIFIER: ("identifier (key, code, choice, hash, URL, date)", "n/a", "n/a", "as an identifier, not prose",
                      "schema and reference checks"),
}  # fmt: skip


def entities() -> dict[str, list[str]]:
    """Which record kinds reach each declaring model."""
    out: dict[str, set[str]] = {}
    for kind, cls in kinds.SCHEMAS.items():
        for decl, _field in text.string_fields([cls]):
            out.setdefault(decl, set()).add(kind)
    return {k: sorted(v) for k, v in out.items()}


def render() -> str:
    reach = entities()
    lines = [
        "# Catalog V3 customer-text inventory (generated)",
        "",
        "Generated by `api/tools/catalog_text_inventory.py` from `veda.modules.catalog.text.FIELD_CLASSES`. Do not edit by",
        "hand: `tests/unit/test_catalog_text_inventory.py` fails when a text field is unclassified or this file is stale.",
        "",
        "Every customer-visible text path is inventoried and is either factual, controlled-copy governed, or",
        "promise-matrix governed. Tests: `test_catalog_text_inventory.py` (registry, stripping, this file) and",
        "`test_catalog_claims.py` (every factual field and statement, aliases, nested fields, import, release gate).",
        "",
        "| Entity (record kinds) | Field | Class | Governed copy | Promise matrix | Public | Release gate |",
        "|---|---|---|---|---|---|---|",
    ]
    for decl, field in sorted(text.string_fields(kinds.SCHEMAS.values())):
        cls = text.FIELD_CLASSES[(decl, field)]
        label, governed, matrix, public, gate = ROWS[cls]
        lines.append(
            f"| {decl} ({', '.join(reach.get(decl, []))}) | `{field}` | {label} | {governed} | {matrix} | {public} | {gate} |"
        )
    lines += ["", "Fields named by the instruction that the catalog does not have (so they carry no text):", ""]
    lines += [f"- {name}" for name in text.NOT_IN_SCHEMA]
    lines += ["", "`Package.recommended` is a boolean; the page does not render it as text. Rendering a recommendation",
              "label would need an approved claim copy record.", ""]  # fmt: skip
    return "\n".join(lines)


if __name__ == "__main__":
    out = render()
    if "--write" in sys.argv:
        DOC.write_text(out)
        print(f"wrote {DOC}")
    else:
        print(out)
