"""Generate the Terraform side of the shared V3 staging approval conformance cases.

The cases (api/tests/fixtures/v3_approval/cases.json) are the single definition of what every approval gate must decide.
Python and Node read them directly; Terraform test files cannot, so this writes one `run` per case into
infra/terraform/modules/v3-approval/tests/conformance.tftest.hcl. A unit test fails when the committed file differs
from what this would write.

    python tools/v3_approval_conformance.py          # rewrite the Terraform test file
    python tools/v3_approval_conformance.py --check  # exit 1 when it is out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CASES = ROOT / "api/tests/fixtures/v3_approval/cases.json"
OUT = ROOT / "infra/terraform/modules/v3-approval/tests/conformance.tftest.hcl"
FROM_MODULE = "../../../../api/tests/fixtures/v3_approval"  # the fixtures, relative to the module directory


def render() -> str:
    spec = json.loads(CASES.read_text())
    out = [
        "# GENERATED by api/tools/v3_approval_conformance.py from api/tests/fixtures/v3_approval/cases.json; do not edit.",
        "# Every case must give exactly the codes the Python validator and the staging build give for it.",
        "",
    ]
    for case in spec["cases"]:
        path = f"{FROM_MODULE}/{case['record']}.json"
        bound = {"record": f'try(filesha256("{path}"), null)', "other": f'"{spec["other_digest"]}"', None: "null"}[
            case["bound"]
        ]
        codes = ", ".join(f'"{c}"' for c in case["codes"])
        out += [
            f'run "{case["name"]}" {{',
            "  command = plan",
            "  variables {",
            f'    record_path  = "{path}"',
            f"    bound_sha256 = {bound}",
            f'    today        = "{case["today"]}"',
            "  }",
            "  assert {",
            f"    condition     = output.codes == [{codes}]",
            f'    error_message = "{case["name"]}: got ${{jsonencode(output.codes)}}"',
            "  }",
            "}",
            "",
        ]
    return "\n".join(out)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is out of date: run python tools/v3_approval_conformance.py")
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
