"""0100_crm_leads: lead, lead_note, lead_activity (04 §2, §9, §10).

Module migrations depend only on platform revisions (02 §8.3).

Revision ID: 0100_crm_leads
Revises: 0008_account_security
"""
import sqlalchemy as sa
from alembic import op

from veda.kernel import migration_support as ms  # noqa: F401
from veda.kernel.types import GUID, JSONType, UTCDateTime  # noqa: F401

revision = "0100_crm_leads"
down_revision = "0008_account_security"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- generated DDL (tools/render_migrations.py) ---
    op.create_table(
        "lead",
        sa.Column('id', GUID(), nullable=False),
        sa.Column('created_on', UTCDateTime(), nullable=False),
        sa.Column('updated_on', UTCDateTime(), nullable=False),
        sa.Column('created_by', GUID(), nullable=False),
        sa.Column('updated_by', GUID(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('deleted_on', UTCDateTime(), nullable=True),
        sa.Column('deleted_by', GUID(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('lead_number', sa.String(20), nullable=False),
        sa.Column('public_reference', sa.CHAR(9), nullable=False),
        sa.Column('name', sa.String(150), nullable=False),
        sa.Column('phone', sa.String(16), nullable=False),
        sa.Column('phone_raw', sa.String(30), nullable=False),
        sa.Column('email', sa.String(254), nullable=True),
        sa.Column('email_normalized', sa.String(254), nullable=True),
        sa.Column('city', sa.String(100), nullable=True),
        sa.Column('locality', sa.String(150), nullable=True),
        sa.Column('project_type_id', GUID(), nullable=True),
        sa.Column('property_type_id', GUID(), nullable=True),
        sa.Column('budget_range_id', GUID(), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='NEW'),
        sa.Column('status_changed_on', UTCDateTime(), nullable=False),
        sa.Column('priority', sa.String(10), nullable=False, server_default='MEDIUM'),
        sa.Column('source_id', GUID(), nullable=False),
        sa.Column('source_detail', sa.String(200), nullable=True),
        sa.Column('utm_source', sa.String(100), nullable=True),
        sa.Column('utm_medium', sa.String(100), nullable=True),
        sa.Column('utm_campaign', sa.String(100), nullable=True),
        sa.Column('utm_term', sa.String(100), nullable=True),
        sa.Column('utm_content', sa.String(100), nullable=True),
        sa.Column('landing_page', sa.String(500), nullable=True),
        sa.Column('referrer_url', sa.String(500), nullable=True),
        sa.Column('assigned_to', GUID(), nullable=True),
        sa.Column('assigned_on', UTCDateTime(), nullable=True),
        sa.Column('next_follow_up_on', UTCDateTime(), nullable=True),
        sa.Column('last_activity_on', UTCDateTime(), nullable=True),
        sa.Column('expected_close_on', sa.Date(), nullable=True),
        sa.Column('quoted_amount_minor', sa.BigInteger(), nullable=True),
        sa.Column('currency', sa.CHAR(3), nullable=False, server_default='INR'),
        sa.Column('won_on', UTCDateTime(), nullable=True),
        sa.Column('lost_on', UTCDateTime(), nullable=True),
        sa.Column('lost_reason_id', GUID(), nullable=True),
        sa.Column('lost_reason_note', sa.String(1000), nullable=True),
        sa.Column('duplicate_status', sa.String(15), nullable=False, server_default='NONE'),
        sa.Column('duplicate_of_lead_id', GUID(), nullable=True),
        sa.Column('consent_contact', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('consent_policy_version', sa.String(20), nullable=True),
        sa.Column('consent_captured_on', UTCDateTime(), nullable=True),
        sa.Column('consent_channel', sa.String(20), nullable=True),
        sa.Column('consent_source_page', sa.String(500), nullable=True),
        sa.Column('consent_ip_address', sa.String(45), nullable=True),
        sa.Column('intake_idempotency_key', sa.String(64), nullable=True),
        sa.Column('intake_request_fingerprint', sa.CHAR(64), nullable=True),
        sa.Column('intake_unmapped', JSONType(), nullable=True),
        sa.Column('spam_status', sa.String(15), nullable=False, server_default='NONE'),
        sa.Column('consent_withdrawn_on', UTCDateTime(), nullable=True),
        sa.Column('consent_withdrawal_channel', sa.String(20), nullable=True),
        sa.Column('consent_withdrawal_note', sa.String(500), nullable=True),
        sa.Column('search_text', sa.Text(), nullable=False, server_default=''),
        sa.Column('anonymized_on', UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_lead"),
        sa.ForeignKeyConstraint(['assigned_to'], ['app_user.id'], name='fk_lead__assigned_to', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['budget_range_id'], ['lookup_value.id'], name='fk_lead__budget_range_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name='fk_lead__created_by', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], name='fk_lead__deleted_by', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['duplicate_of_lead_id'], ['lead.id'], name='fk_lead__duplicate_of_lead_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['lost_reason_id'], ['lookup_value.id'], name='fk_lead__lost_reason_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['project_type_id'], ['lookup_value.id'], name='fk_lead__project_type_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['property_type_id'], ['lookup_value.id'], name='fk_lead__property_type_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['source_id'], ['lookup_value.id'], name='fk_lead__source_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name='fk_lead__updated_by', ondelete='RESTRICT'),
        sa.CheckConstraint('(assigned_to IS NULL) = (assigned_on IS NULL)', name='ck_lead__assigned_consistency'),
        sa.CheckConstraint("assigned_to IS NULL OR (length(assigned_to) = 32 AND assigned_to NOT GLOB '*[^0-9a-f]*' AND substr(assigned_to, 13, 1) = '7' AND substr(assigned_to, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead__assigned_to_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("budget_range_id IS NULL OR (length(budget_range_id) = 32 AND budget_range_id NOT GLOB '*[^0-9a-f]*' AND substr(budget_range_id, 13, 1) = '7' AND substr(budget_range_id, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead__budget_range_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(city) <= 100', name='ck_lead__city_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("consent_channel IS NULL OR consent_channel IN ('WEBSITE_FORM', 'PHONE_VERBAL', 'IN_PERSON', 'WHATSAPP', 'EMAIL')", name='ck_lead__consent_channel'),
        sa.CheckConstraint('length(consent_channel) <= 20', name='ck_lead__consent_channel_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('consent_contact = false OR (consent_policy_version IS NOT NULL AND consent_captured_on IS NOT NULL AND consent_channel IS NOT NULL)', name='ck_lead__consent_complete'),
        sa.CheckConstraint('consent_contact IN (0, 1)', name='ck_lead__consent_contact_bool').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(consent_ip_address) <= 45', name='ck_lead__consent_ip_address_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(consent_policy_version) <= 20', name='ck_lead__consent_policy_version_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(consent_source_page) <= 500', name='ck_lead__consent_source_page_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("consent_withdrawal_channel IS NULL OR consent_withdrawal_channel IN ('PHONE_VERBAL', 'IN_PERSON', 'WHATSAPP', 'EMAIL', 'WEBSITE')", name='ck_lead__consent_withdrawal_channel'),
        sa.CheckConstraint('length(consent_withdrawal_channel) <= 20', name='ck_lead__consent_withdrawal_channel_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(consent_withdrawal_note) <= 500', name='ck_lead__consent_withdrawal_note_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("length(created_by) = 32 AND created_by NOT GLOB '*[^0-9a-f]*' AND substr(created_by, 13, 1) = '7' AND substr(created_by, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead__created_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(currency) <= 3', name='ck_lead__currency_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("deleted_by IS NULL OR (length(deleted_by) = 32 AND deleted_by NOT GLOB '*[^0-9a-f]*' AND substr(deleted_by, 13, 1) = '7' AND substr(deleted_by, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead__deleted_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("duplicate_of_lead_id IS NULL OR (length(duplicate_of_lead_id) = 32 AND duplicate_of_lead_id NOT GLOB '*[^0-9a-f]*' AND substr(duplicate_of_lead_id, 13, 1) = '7' AND substr(duplicate_of_lead_id, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead__duplicate_of_lead_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("duplicate_status IN ('NONE', 'SUSPECTED', 'CONFIRMED', 'NOT_DUPLICATE')", name='ck_lead__duplicate_status'),
        sa.CheckConstraint('length(duplicate_status) <= 15', name='ck_lead__duplicate_status_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(email) <= 254', name='ck_lead__email_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(email_normalized) <= 254', name='ck_lead__email_normalized_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("length(id) = 32 AND id NOT GLOB '*[^0-9a-f]*' AND substr(id, 13, 1) = '7' AND substr(id, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead__id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(intake_idempotency_key) <= 64', name='ck_lead__intake_idempotency_key_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(intake_request_fingerprint) <= 64', name='ck_lead__intake_request_fingerprint_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('intake_unmapped IS NULL OR json_valid(intake_unmapped)', name='ck_lead__intake_unmapped_json').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('is_deleted IN (0, 1)', name='ck_lead__is_deleted_bool').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(landing_page) <= 500', name='ck_lead__landing_page_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(lead_number) <= 20', name='ck_lead__lead_number_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(locality) <= 150', name='ck_lead__locality_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("(status = 'LOST') = (lost_on IS NOT NULL AND lost_reason_id IS NOT NULL)", name='ck_lead__lost_consistency'),
        sa.CheckConstraint("lost_reason_id IS NULL OR (length(lost_reason_id) = 32 AND lost_reason_id NOT GLOB '*[^0-9a-f]*' AND substr(lost_reason_id, 13, 1) = '7' AND substr(lost_reason_id, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead__lost_reason_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(lost_reason_note) <= 1000', name='ck_lead__lost_reason_note_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(message) <= 4000', name='ck_lead__message_len'),
        sa.CheckConstraint('length(name) <= 150', name='ck_lead__name_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('duplicate_of_lead_id IS NULL OR duplicate_of_lead_id <> id', name='ck_lead__not_self_duplicate'),
        sa.CheckConstraint('length(phone) <= 16', name='ck_lead__phone_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(phone_raw) <= 30', name='ck_lead__phone_raw_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("priority IN ('HIGH', 'MEDIUM', 'LOW')", name='ck_lead__priority'),
        sa.CheckConstraint('length(priority) <= 10', name='ck_lead__priority_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("project_type_id IS NULL OR (length(project_type_id) = 32 AND project_type_id NOT GLOB '*[^0-9a-f]*' AND substr(project_type_id, 13, 1) = '7' AND substr(project_type_id, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead__project_type_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("property_type_id IS NULL OR (length(property_type_id) = 32 AND property_type_id NOT GLOB '*[^0-9a-f]*' AND substr(property_type_id, 13, 1) = '7' AND substr(property_type_id, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead__property_type_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(public_reference) <= 9', name='ck_lead__public_reference_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('quoted_amount_minor IS NULL OR quoted_amount_minor >= 0', name='ck_lead__quoted_amount'),
        sa.CheckConstraint('length(referrer_url) <= 500', name='ck_lead__referrer_url_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('(is_deleted = false AND deleted_on IS NULL AND deleted_by IS NULL) OR (is_deleted = true AND deleted_on IS NOT NULL AND deleted_by IS NOT NULL)', name='ck_lead__soft_delete_consistent'),
        sa.CheckConstraint('length(source_detail) <= 200', name='ck_lead__source_detail_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("length(source_id) = 32 AND source_id NOT GLOB '*[^0-9a-f]*' AND substr(source_id, 13, 1) = '7' AND substr(source_id, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead__source_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("spam_status IN ('NONE', 'SUSPECTED', 'CONFIRMED_SPAM', 'NOT_SPAM')", name='ck_lead__spam_status'),
        sa.CheckConstraint('length(spam_status) <= 15', name='ck_lead__spam_status_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("status IN ('NEW', 'CONTACTED', 'SITE_VISIT', 'QUOTATION_SENT', 'NEGOTIATION', 'WON', 'LOST')", name='ck_lead__status'),
        sa.CheckConstraint('length(status) <= 20', name='ck_lead__status_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('updated_on >= created_on', name='ck_lead__updated_after_created'),
        sa.CheckConstraint("length(updated_by) = 32 AND updated_by NOT GLOB '*[^0-9a-f]*' AND substr(updated_by, 13, 1) = '7' AND substr(updated_by, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead__updated_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(utm_campaign) <= 100', name='ck_lead__utm_campaign_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(utm_content) <= 100', name='ck_lead__utm_content_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(utm_medium) <= 100', name='ck_lead__utm_medium_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(utm_source) <= 100', name='ck_lead__utm_source_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(utm_term) <= 100', name='ck_lead__utm_term_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('version >= 1', name='ck_lead__version_positive'),
        sa.CheckConstraint('consent_withdrawn_on IS NULL OR (consent_contact = false AND consent_withdrawal_channel IS NOT NULL)', name='ck_lead__withdrawal_consistency'),
        sa.CheckConstraint("(status = 'WON') = (won_on IS NOT NULL)", name='ck_lead__won_consistency'),
    )
    op.create_index('ix_lead__assigned_status', "lead", ['assigned_to', 'status', sa.text('created_on DESC')], sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_lead__created_by', "lead", ['created_by'], sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_lead__created_on', "lead", [sa.text('created_on DESC')])
    op.create_index('ix_lead__email_normalized', "lead", ['email_normalized'], sqlite_where=sa.text('email_normalized IS NOT NULL AND is_deleted = 0'), postgresql_where=sa.text('email_normalized IS NOT NULL AND is_deleted = false'))
    op.create_index('ix_lead__next_follow_up', "lead", ['next_follow_up_on'], sqlite_where=sa.text("status NOT IN ('WON','LOST') AND is_deleted = 0"), postgresql_where=sa.text("status NOT IN ('WON','LOST') AND is_deleted = false"))
    op.create_index('ix_lead__phone', "lead", ['phone'], sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_lead__retention', "lead", ['status', 'status_changed_on'], sqlite_where=sa.text("status IN ('WON','LOST') AND anonymized_on IS NULL"), postgresql_where=sa.text("status IN ('WON','LOST') AND anonymized_on IS NULL"))
    op.create_index('ix_lead__source', "lead", ['source_id', sa.text('created_on DESC')], sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_lead__spam_queue', "lead", ['spam_status', sa.text('created_on DESC')], sqlite_where=sa.text("spam_status = 'SUSPECTED' AND is_deleted = 0"), postgresql_where=sa.text("spam_status = 'SUSPECTED' AND is_deleted = false"))
    op.create_index('ix_lead__status_created', "lead", ['status', sa.text('created_on DESC')], sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ux_lead__intake_idempotency_key', "lead", ['intake_idempotency_key'], unique=True, sqlite_where=sa.text('intake_idempotency_key IS NOT NULL'), postgresql_where=sa.text('intake_idempotency_key IS NOT NULL'))
    op.create_index('ux_lead__lead_number', "lead", ['lead_number'], unique=True, sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ux_lead__public_reference', "lead", ['public_reference'], unique=True)

    op.create_table(
        "lead_note",
        sa.Column('id', GUID(), nullable=False),
        sa.Column('created_on', UTCDateTime(), nullable=False),
        sa.Column('updated_on', UTCDateTime(), nullable=False),
        sa.Column('created_by', GUID(), nullable=False),
        sa.Column('updated_by', GUID(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('deleted_on', UTCDateTime(), nullable=True),
        sa.Column('deleted_by', GUID(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('lead_id', GUID(), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('visibility', sa.String(20), nullable=False, server_default='INTERNAL'),
        sa.PrimaryKeyConstraint("id", name="pk_lead_note"),
        sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name='fk_lead_note__created_by', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], name='fk_lead_note__deleted_by', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name='fk_lead_note__lead_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name='fk_lead_note__updated_by', ondelete='RESTRICT'),
        sa.CheckConstraint('length(body) BETWEEN 1 AND 10000', name='ck_lead_note__body_len'),
        sa.CheckConstraint("length(created_by) = 32 AND created_by NOT GLOB '*[^0-9a-f]*' AND substr(created_by, 13, 1) = '7' AND substr(created_by, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_note__created_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("deleted_by IS NULL OR (length(deleted_by) = 32 AND deleted_by NOT GLOB '*[^0-9a-f]*' AND substr(deleted_by, 13, 1) = '7' AND substr(deleted_by, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead_note__deleted_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("length(id) = 32 AND id NOT GLOB '*[^0-9a-f]*' AND substr(id, 13, 1) = '7' AND substr(id, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_note__id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('is_deleted IN (0, 1)', name='ck_lead_note__is_deleted_bool').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('is_pinned IN (0, 1)', name='ck_lead_note__is_pinned_bool').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("length(lead_id) = 32 AND lead_id NOT GLOB '*[^0-9a-f]*' AND substr(lead_id, 13, 1) = '7' AND substr(lead_id, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_note__lead_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('(is_deleted = false AND deleted_on IS NULL AND deleted_by IS NULL) OR (is_deleted = true AND deleted_on IS NOT NULL AND deleted_by IS NOT NULL)', name='ck_lead_note__soft_delete_consistent'),
        sa.CheckConstraint('updated_on >= created_on', name='ck_lead_note__updated_after_created'),
        sa.CheckConstraint("length(updated_by) = 32 AND updated_by NOT GLOB '*[^0-9a-f]*' AND substr(updated_by, 13, 1) = '7' AND substr(updated_by, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_note__updated_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('version >= 1', name='ck_lead_note__version_positive'),
        sa.CheckConstraint("visibility IN ('INTERNAL', 'CUSTOMER_VISIBLE')", name='ck_lead_note__visibility'),
        sa.CheckConstraint('length(visibility) <= 20', name='ck_lead_note__visibility_len').ddl_if(dialect="sqlite"),
    )
    op.create_index('ix_lead_note__created_by', "lead_note", ['created_by'], sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_lead_note__lead_created', "lead_note", ['lead_id', sa.text('is_pinned DESC'), sa.text('created_on DESC')], sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))

    op.create_table(
        "lead_activity",
        sa.Column('id', GUID(), nullable=False),
        sa.Column('created_on', UTCDateTime(), nullable=False),
        sa.Column('updated_on', UTCDateTime(), nullable=False),
        sa.Column('created_by', GUID(), nullable=False),
        sa.Column('updated_by', GUID(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('deleted_on', UTCDateTime(), nullable=True),
        sa.Column('deleted_by', GUID(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('lead_id', GUID(), nullable=False),
        sa.Column('activity_type', sa.String(20), nullable=False),
        sa.Column('is_system_generated', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('activity_status', sa.String(12), nullable=False, server_default='COMPLETED'),
        sa.Column('subject', sa.String(200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('direction', sa.String(10), nullable=True),
        sa.Column('scheduled_on', UTCDateTime(), nullable=True),
        sa.Column('completed_on', UTCDateTime(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=True),
        sa.Column('outcome_id', GUID(), nullable=True),
        sa.Column('owner_user_id', GUID(), nullable=False),
        sa.Column('location', sa.String(300), nullable=True),
        sa.Column('from_status', sa.String(20), nullable=True),
        sa.Column('to_status', sa.String(20), nullable=True),
        sa.Column('cancelled_reason', sa.String(300), nullable=True),
        sa.Column('metadata', JSONType(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_lead_activity"),
        sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name='fk_lead_activity__created_by', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], name='fk_lead_activity__deleted_by', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name='fk_lead_activity__lead_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['outcome_id'], ['lookup_value.id'], name='fk_lead_activity__outcome_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name='fk_lead_activity__owner_user_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name='fk_lead_activity__updated_by', ondelete='RESTRICT'),
        sa.CheckConstraint('length(activity_status) <= 12', name='ck_lead_activity__activity_status_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(activity_type) <= 20', name='ck_lead_activity__activity_type_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(cancelled_reason) <= 300', name='ck_lead_activity__cancelled_reason_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("activity_status <> 'COMPLETED' OR completed_on IS NOT NULL", name='ck_lead_activity__completed_has_time'),
        sa.CheckConstraint("length(created_by) = 32 AND created_by NOT GLOB '*[^0-9a-f]*' AND substr(created_by, 13, 1) = '7' AND substr(created_by, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_activity__created_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("deleted_by IS NULL OR (length(deleted_by) = 32 AND deleted_by NOT GLOB '*[^0-9a-f]*' AND substr(deleted_by, 13, 1) = '7' AND substr(deleted_by, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead_activity__deleted_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(description) <= 4000', name='ck_lead_activity__description_len'),
        sa.CheckConstraint("direction IS NULL OR direction IN ('INBOUND', 'OUTBOUND')", name='ck_lead_activity__direction'),
        sa.CheckConstraint('length(direction) <= 10', name='ck_lead_activity__direction_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes BETWEEN 0 AND 1440', name='ck_lead_activity__duration'),
        sa.CheckConstraint("from_status IS NULL OR from_status IN ('NEW', 'CONTACTED', 'SITE_VISIT', 'QUOTATION_SENT', 'NEGOTIATION', 'WON', 'LOST')", name='ck_lead_activity__from_status'),
        sa.CheckConstraint('length(from_status) <= 20', name='ck_lead_activity__from_status_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("length(id) = 32 AND id NOT GLOB '*[^0-9a-f]*' AND substr(id, 13, 1) = '7' AND substr(id, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_activity__id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('is_deleted IN (0, 1)', name='ck_lead_activity__is_deleted_bool').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('is_system_generated IN (0, 1)', name='ck_lead_activity__is_system_generated_bool').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("length(lead_id) = 32 AND lead_id NOT GLOB '*[^0-9a-f]*' AND substr(lead_id, 13, 1) = '7' AND substr(lead_id, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_activity__lead_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('length(location) <= 300', name='ck_lead_activity__location_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('metadata IS NULL OR json_valid(metadata)', name='ck_lead_activity__metadata_json').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("outcome_id IS NULL OR (length(outcome_id) = 32 AND outcome_id NOT GLOB '*[^0-9a-f]*' AND substr(outcome_id, 13, 1) = '7' AND substr(outcome_id, 17, 1) IN ('8', '9', 'a', 'b'))", name='ck_lead_activity__outcome_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("length(owner_user_id) = 32 AND owner_user_id NOT GLOB '*[^0-9a-f]*' AND substr(owner_user_id, 13, 1) = '7' AND substr(owner_user_id, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_activity__owner_user_id_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("activity_status <> 'PLANNED' OR scheduled_on IS NOT NULL", name='ck_lead_activity__planned_has_schedule'),
        sa.CheckConstraint('(is_deleted = false AND deleted_on IS NULL AND deleted_by IS NULL) OR (is_deleted = true AND deleted_on IS NOT NULL AND deleted_by IS NOT NULL)', name='ck_lead_activity__soft_delete_consistent'),
        sa.CheckConstraint("activity_status IN ('PLANNED', 'COMPLETED', 'CANCELLED')", name='ck_lead_activity__status'),
        sa.CheckConstraint("activity_type <> 'STATUS_CHANGE' OR (from_status IS NOT NULL AND to_status IS NOT NULL)", name='ck_lead_activity__status_change_fields'),
        sa.CheckConstraint('length(subject) <= 200', name='ck_lead_activity__subject_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("to_status IS NULL OR to_status IN ('NEW', 'CONTACTED', 'SITE_VISIT', 'QUOTATION_SENT', 'NEGOTIATION', 'WON', 'LOST')", name='ck_lead_activity__to_status'),
        sa.CheckConstraint('length(to_status) <= 20', name='ck_lead_activity__to_status_len').ddl_if(dialect="sqlite"),
        sa.CheckConstraint("activity_type IN ('CALL', 'WHATSAPP', 'EMAIL', 'MEETING', 'SITE_VISIT', 'QUOTATION', 'FOLLOW_UP', 'STATUS_CHANGE', 'ASSIGNMENT', 'SYSTEM')", name='ck_lead_activity__type'),
        sa.CheckConstraint('updated_on >= created_on', name='ck_lead_activity__updated_after_created'),
        sa.CheckConstraint("length(updated_by) = 32 AND updated_by NOT GLOB '*[^0-9a-f]*' AND substr(updated_by, 13, 1) = '7' AND substr(updated_by, 17, 1) IN ('8', '9', 'a', 'b')", name='ck_lead_activity__updated_by_format').ddl_if(dialect="sqlite"),
        sa.CheckConstraint('version >= 1', name='ck_lead_activity__version_positive'),
    )
    op.create_index('ix_lead_activity__lead_planned', "lead_activity", ['lead_id', 'scheduled_on'], sqlite_where=sa.text("activity_status = 'PLANNED' AND is_deleted = 0"), postgresql_where=sa.text("activity_status = 'PLANNED' AND is_deleted = false"))
    op.create_index('ix_lead_activity__lead_timeline', "lead_activity", ['lead_id', sa.text('created_on DESC')], sqlite_where=sa.text('is_deleted = 0'), postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_lead_activity__owner_planned', "lead_activity", ['owner_user_id', 'scheduled_on'], sqlite_where=sa.text("activity_status = 'PLANNED' AND is_deleted = 0"), postgresql_where=sa.text("activity_status = 'PLANNED' AND is_deleted = false"))
    # --- end generated DDL ---
    pass


def downgrade() -> None:
    # Expand-only migrations; no down-migrations are relied on (02 §12.4).
    raise NotImplementedError("down-migrations are not supported")

